### ISSUE TITLE
Conflict with FormFocus

### ISSUE THREAD

**Issue by SiamKreative** [ThemeAvenue/BetterOptin#29]
If https://github.com/ThemeAvenue/Form-Focus is enabled, the modal's form gets the class `.formbox-active`, which does this:
```css
.formbox-active {
    z-index: 1000;
    position: relative;
}
```

Therefore, the overlay is on top of the modal itself.
